footer:
  since: 2015
  beian:
    enable: true
    icp: '鲁ICP备13027795号-1'
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  about: /about.html || fa fa-user
darkmode: true
